### PR TITLE
fix: Improve Static Server Reliability

### LINKED ISSUE #4: Cannot serve `.webp` image in `mdx`
I'm using `hybrid` mode with `mdx` to render the blog content.

With `@astrojs/node`, the production build serves the image with `.webp` normally.
But with `astro-bun`, it is always **404 not found** for images in `webp` format.

I checked with the `png` version of the same image, it serves normally.
I also ensured the `webp` version of the image was not broken.

```mdx
[//]: # Sample mdx file in the content folder
import { Image } from 'astro:assets';

import ImageCAT6Cable from './cat6-cable.png';

some markdown content here

<figure>
  <Image
    loading={'lazy'}
    src={ImageCAT6Cable}
    alt="cat6 cable" />
  <figcaption>some caption</figcaption>
</figure>

some markdown content here
```

The image resolved to the correct path (`/_astro/cat6-cable<random>.webp`) but returns 404.
If I change the image path directly to the PNG version (`/_astro/cat6-cable<random>.png`), it will work just fine.

### PR DESCRIPTION
**Pull request by lilnasy**
# Changes
- Closes #4
- Astro SSR manifest is not exactly public API. If it works it works, but if it doesn't we should use something else.
- In this case, optimized images are not included in the "assets" list, which the adapter relied upon.
- Updated the logic to read the client directory on server boot and use the found files instead of the assets list in the SSR manifest.

image

### CODE REVIEW

File: package/src/index.ts [hunk 1]
```diff
@@ -30,23 +27,31 @@ export function getAdapter(args: Options = {}): AstroAdapter {
...
-  setup: (integration) => ({
+export default (options?: Options): AstroIntegration => {
+  if (options) {
+    if (options.cluster && typeof options.cluster !== "boolean") {
+      throw new Error(`[${packageName}] options.cluster must be a boolean, but the adapter was provided with ${options.cluster} instead.`)
+    }
+    if (options.unix && typeof options.unix !== "string") {
+      throw new Error(`[${packageName}] options.unix must be a string, but the adapter was provided with ${options.unix} instead.`)
+    }
+  }
```
Comment (NuroDev) [inline package/src/index.ts:38]: Please restore using `defineIntegration` with the `OptionsSchema` for this as it makes managing the validation of everything cleaner and easier to manage long time.

Instead of having an `if` check for every option just update the `OptionsSchema` to include the `unix` property.

File: package/src/index.ts [hunk 2]
```diff
@@ -30,23 +27,31 @@ export function getAdapter(args: Options = {}): AstroAdapter {
...
+  return {
+    name: packageName,
     hooks: {
-      'astro:config:done': (params) => {
+      'astro:config:done': params => {
```
Comment (NuroDev) [inline package/src/index.ts:42]: Please make sure to run the `format` and/or `lint` scripts to format the code correctly.

File: package/src/server/index.ts [hunk 3]
```diff
@@ -43,16 +46,27 @@ export function start(manifest: SSRManifest, options: Options): void {
...
+      _server = Bun.serve({
+        error: (error) =>
+          new Response(`<pre>${error}\n${error.stack}</pre>`, {
+            headers: { 'Content-Type': 'text/html' },
+          }),
+        fetch: handler(manifest, options),
+        hostname,
+        port,
+      });
+    }
```
Comment (NuroDev) [inline package/src/server/index.ts:69]: This could probably be simplified into an object spread with a ternary like so:
```ts
_server = Bun.serve({
	error: (error) => new Response(`<pre>${error}\n${error.stack}</pre>`, {
		headers: { 'Content-Type': 'text/html' },
	}),
	fetch: handler(manifest, options),
	...(unix ? {
		unix,
	} : {
		hostname,
		port,
	})
});
```

File: package/src/server/index.ts [hunk 4]
```diff
@@ -106,3 +127,44 @@ function handler(
     });
   };
 }
+
+async function getStaticAssets(clientDir: string) {
```
Comment (NuroDev) [inline package/src/server/index.ts:131]:
```suggestion
async function getStaticAssets(clientDir: string): Promise<Set<string>> {
```

File: package/src/server/index.ts [hunk 5]
```diff
@@ -106,3 +127,44 @@ function handler(
...
+    serverEntryFolderURL = path.dirname(serverEntryFolderURL);
+  }
+
+  const serverEntryURL = serverEntryFolderURL + '/entry.mjs';
+  const clientURL = new URL(appendForwardSlash(rel), serverEntryURL);
+  const client = url.fileURLToPath(clientURL);
+  return client;
+}
+
+function prependForwardSlash(pth: string) {
```
Comment (NuroDev) [inline package/src/server/index.ts:164]:
```suggestion
function prependForwardSlash(pth: string): string {
```

File: package/src/server/index.ts [hunk 6]
```diff
@@ -106,3 +127,44 @@ function handler(
...
+  return pth.startsWith('/') ? pth : '/' + pth;
+}
+
+function appendForwardSlash(pth: string) {
```
Comment (NuroDev) [inline package/src/server/index.ts:168]:
```suggestion
function appendForwardSlash(pth: string): string {
```

File: package/src/server/index.ts [hunk 7]
```diff
@@ -106,3 +127,44 @@ function handler(
...
+  }
+  return publicPath
+}
+
+/**
+ * From https://github.com/withastro/adapters/blob/@astrojs/node@9.0.0/packages/node/src/serve-static.ts#L109-L125
+ * 
+ * Copyright of withastro/adapters contributors, Reproduced under MIT License
+ */
+function resolveClientDir(options: InternalOptions) {
```
Comment (NuroDev) [inline package/src/server/index.ts:146]:
```suggestion
function resolveClientDir(options: InternalOptions): string {
```

File: package/src/server/index.ts [hunk 8]
```diff
@@ -106,3 +127,44 @@ function handler(
...
+  const clientURLRaw = new URL(options.client);
+  const serverURLRaw = new URL(options.server);
+  const rel = path.relative(url.fileURLToPath(serverURLRaw), url.fileURLToPath(clientURLRaw));
+
+  // walk up the parent folders until you find the one that is the root of the server entry folder. This is how we find the client folder relatively.
```
Comment (NuroDev) [inline package/src/server/index.ts:151]:
```suggestion
  // Walk up the parent folders until you find the one that is the root of the server entry folder. This is how we find the client folder relatively.
```

File: package/src/types.ts
Comment (NuroDev) [inline package/src/types.ts:1]: All of the changes here seem to replace & ignore the Zod validation schemas in `package/src/validators.ts`?

**Review by NuroDev — CHANGES_REQUESTED** [review]

**Comment by NuroDev** [comment]
It also seems you have based this branch off of your branch used for #10 so the 2 you've put 2 PR's into 1.

File: package/package.json
[the remark this answers is not in the document]
Comment (lilnasy) [reply package/package.json:1]: This is from https://github.com/NuroDev/astro-bun/pull/10. The reasoning was tsup.

image

File: package/src/index.ts (hunk 1 above)
Comment (lilnasy) [reply package/src/index.ts:38]: Sure. How should the options be documented instead?

Since zod schemas can't directly be used to infer type while maintaining type docs, astro defines the configuration twice: once as the zod schema, and once as the typescript interface.

File: package/src/types.ts
Comment (lilnasy) [reply package/src/types.ts:1]: Yes, that's somewhat intentional.

Using `z.infer` would remove hover documentation. So rewriting the schema as an interface is necessary. Astro's config does the same.

Additionally, so far they were only being used to validate internal options (assets, host, port), which were ignored if provided by the user. So their presence in the options schema is also misleading. For example `adapter: bun({ port: 80 })` has never had any effect but it was present in the adapter parameter types anyway.

File: package/package.json
[the remark this answers is not in the document]
Comment (NuroDev) [reply package/package.json:1]: Ah okay, that makes sense 👍

File: package/src/index.ts (hunk 1 above)
Comment (NuroDev) [reply package/src/index.ts:38]: The existing Zod schema documentation system does infer the type docs.
CleanShot 2024-12-23 at 11  48 19@2x

Comment (lilnasy) [reply package/src/index.ts]: That's great! I'll edit the other PR.

Comment (NuroDev) [reply package/src/index.ts]: Ah I see what you mean now. In the bundled types don't infer / copy the type docs.
CleanShot 2024-12-23 at 11  54 08@2x

In which case I'll push a new updated `Options` type structure that should fix this.

Comment (lilnasy) [reply package/src/index.ts]: It'd be great if you could add that as a commit to #10.

The corrected types for internal options are needed here in this PR:

https://github.com/NuroDev/astro-bun/pull/11/files#diff-218e1f81d8eccf28a9144e1b876a38b8dd3da491146e981e5816c8c48fd6afcdR138

**Comment by lilnasy** [comment]
Marking as draft because it depends on types being corrected in #11.

**Comment by NuroDev** [comment]
I've just gone ahead and published version `2.1.0` which adds unix socket support.
If you can fix the conflict / comments above I'll get this merged and published.

**Comment by adworacz** [comment]
> I've just gone ahead and published version 2.1.0 which adds unix socket support.

Awesome, thank you very much for this!
